### ISSUE TITLE
cant start the program

### ISSUE THREAD

**Issue by lstxmu** [wpwupingwp/novowrap#1] opened 2020-10-17 13:14 UTC

**Comment by lstxmu** [comment] 2020-10-17 13:15
ImportError: Bio.Alphabet has been removed from Biopython. In many cases, the alphabet can simply be ignored and removed from scripts. In a few cases, you may need to specify the ``molecule_type`` as an annotation on a SeqRecord for your script to work correctly. Please see https://biopython.org/wiki/Alphabet for more information.

**Comment by wpwupingwp** [comment] 2020-10-17 16:01
Duplicate of #2

**Closed by wpwupingwp** 2020-10-17 16:01 UTC
